### ISSUE TITLE
Header File linking error with custom component

### ISSUE THREAD

**Issue by swampyclark** [esphome/ESPHome#378]
**Operating environment (Hass.io/Docker/pip/etc.):**

Pi 3 HASSIO 0.86.0b0
**ESP (ESP32/ESP8266/Board/Sonoff):**

Node MCU
**Affected component:**

https://esphomelib.com/esphomeyaml/custom/uart.html

**Description of problem:**
Using the include in the yaml config file results in a unlinkable header in main.cpp.  Validate will pass but you can not compile.   

**Problem-relevant YAML-configuration entries:**
```yaml
esphomeyaml:
  name: alarm
  platform: ESP8266
  board: nodemcuv2
  includes:
   - my_custom_component.h

```

**Traceback (if applicable):**

```
src/main.cpp:5:42: fatal error: ../../../my_custom_component.h: No such file or directory
#include "../../../my_custom_component.h"
^
compilation terminated.
*** [.pioenvs/alarm/src/main.cpp.o] Error 1
```

**Additional information:**
current work around, put the header file in
/config/esphomeyaml/alarm/.piolibdeps/esphomelib/src/esphomelib/my_custom_component.h
with alarm being my component name
and comment out the include statement in yaml file
