### ISSUE TITLE
Remote Transmitter Switch does not support Sony codes fully

### ISSUE THREAD

**Issue by chris-jennings** [esphome/ESPHome#387]
**Operating environment (Hass.io/Docker/pip/etc.):**
Ubuntu linux with running esphome in a python2 virtual environment

**ESP (ESP32/ESP8266/Board/Sonoff):**
WeMos D1 mini lite

**Affected component:**
Remote Transmitter Switch (in particular Sony remote support)
[Remote Transmitter](https://esphomelib.com/esphomeyaml/components/switch/remote_transmitter.html)

**Description of problem:**
I have successfully installed the WeMod D1 mini lite hardware for both collecting IR codes and transmitting IR codes. I have managed to get my Harmon Kardon receiver to work with the NEC codes that I was able to collect.

I tried to continue this process with my Sony TV and I didn't have any luck. I understand that the Sony TV requires 3 repeats of the same code with a delay between each repeat. I attempted this using the following yaml entry:

```
switch:
  - platform: remote_transmitter
    name: "Sony TV Power"
    sony:
      data: 0x00000A90
      nbits: 12
    repeat: 3
  - platform: remote_transmitter
    name: "Sony TV Volume Up"
    sony:
      data: 0x00000490
      nbits: 12
    repeat: 3
  - platform: remote_transmitter
    name: "Sony TV Volume Down"
    sony:
      data: 0x00000C90
      nbits: 12
```

I get no response using this method.

I looked at other esp8266 projects used for IR remote control and found this one:
[ESP8266-HTTP-IR-Blaster](https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster)
Using that code and reprogramming the same hardware with this system allowed to me successfully send a power on signal to the Sony TV. However I needed to use the following request:
`http://192.168.86.94/msg?code=A90:SONY:12&pulse=3&pdelay=100&pass=1234&simple=1`

This sends the same Sony A90 code, but three times and a delay between repeats of 100ms. I believe that the Sony  remote_transmitter entry requires these extra parameters to enable it to work in some cases.

**Problem-relevant YAML-configuration entries:**
```yaml
esphomeyaml:
  name: wemos2
  platform: ESP8266
  board: d1_mini_lite

wifi:
  ssid: ''
  password: ''

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: remote_transmitter
    name: "Sony TV Power"
    sony:
      data: 0x00000A90
      nbits: 12
    repeat: 3
  - platform: remote_transmitter
    name: "Sony TV Volume Up"
    sony:
      data: 0x00000490
      nbits: 12
    repeat: 3
  - platform: remote_transmitter
    name: "Sony TV Volume Down"
    sony:
      data: 0x00000C90
      nbits: 12
    repeat: 3
  - platform: remote_transmitter
    name: "Sony TV Source"
    sony:
      data: 0x00000A50
      nbits: 12
    repeat: 3
  - platform: remote_transmitter
    name: "Sony TV Menu"
    sony:
      data: 0x00000070
      nbits: 12
    repeat: 3
  - platform: remote_transmitter
    name: "Sony TV Menu Up"
    sony:
      data: 0x000002F0
      nbits: 12
    repeat: 3
  - platform: remote_transmitter
    name: "Sony TV Menu Down"
    sony:
      data: 0x00000AF0
      nbits: 12
    repeat: 3
  - platform: remote_transmitter
    name: "Sony TV Menu Select"
    sony:
      data: 0x00000A70
      nbits: 12
    repeat: 3
  - platform: remote_transmitter
    name: "IR TX1 Amplifier On"
    nec:
      address: 0x010E
      command: 0x03FC
  - platform: remote_transmitter
    name: "IR TX1 Amplifier Off"
    nec:
      address: 0x010E
      command: 0xF906

remote_transmitter:
  pin: D5
  carrier_duty_percent: 50%

```

**Traceback (if applicable):**

```

```

**Additional information:**
Sorry I couldn't trace this back to the code and work it out. I'm not up to speed with Python.
