### ISSUE TITLE
Neopixelbus not working

### ISSUE THREAD

**Issue by TypQxQ** [esphome/ESPHome#389]
**Operating environment (Hass.io):

**ESP (Sonoff basic):**

**Affected component:**
NeoPixelBus

**Description of problem:**
Ledstrip SK6812 RGBW. Have no response when activating with neopixelbus.
Works with Tasmota and it is lighting up and dimming, although wrong colors with fastled_clockless.

**Problem-relevant YAML-configuration entries:**
This does nothing.
```yaml
light:
  - platform: neopixelbus
    type: BRG #GRBW
    pin: GPIO14
    num_leds: 10 #304
    name: ${upper_devicename} Ljus
    variant: SK6812
```
This lights up the leds and I can change color and dim them, although wrong colors.
```yaml
light:
  - platform: fastled_clockless
    chipset: WS2811
    pin: GPIO14
    num_leds: 10
    rgb_order: BRG
    name: ${upper_devicename} Ljus
```

**Traceback (if applicable):**

```

```

**Additional information:**
