### ISSUE TITLE
Combination of CustomComponent and on_json_message lambda gives compile errors.

### ISSUE THREAD

**Issue by mvturnho** [esphome/esphome#404]
**Operating environment (Hass.io/Docker/pip/etc.):**

Windows 10 commandline and platformio Visua lC++
**ESP (ESP32/ESP8266/Board/Sonoff):**

ESP8266 nodemcu 
**Affected component:**

https://esphomelib.com/esphomeyaml/custom/custom_component.html

**Description of problem:**
When I compile the yaml  using the commandline I get compile errors. 
When I leave out the on_json_message lamda from the yaml file it compiles fine. 
Also when I leave out the custom component from the yaml file it compiles fine. 

I want to start implementing the MPR121 touch sensor using a custom component. And this node should have the statusleds. functional, becouse should function as the controlpanel.

commandline
`esphomeyaml controlpanel.yaml compile`

And my `my_custom_sensor.h` file I used that straight from the example documentation.

```cpp
#include "esphomelib.h"
using namespace esphomelib;

class MyCustomComponent : public Component {
 public:
  void setup() override {
    // This will be called once to set up the component
    // think of it as the setup() call in Arduino
    pinMode(5, INPUT);
    pinMode(6, OUTPUT);
  }
  void loop() override {
    // This will be called very often after setup time.
    // think of it as the loop() call in Arduino
    if (digitalRead(5)) {
      digitalWrite(6, HIGH);

      // You can also log messages
      ESP_LOGD("custom", "The GPIO pin 5 is HIGH!");
    }
  }
};
```

**Problem-relevant YAML-configuration entries:**
```yaml
esphomeyaml:
  name: controlpanel
  platform: ESP8266
  board: nodemcuv2
  esphomelib_version:
    branch: dev
  includes:
    - controlpanel/src/my_custom_sensor.h

wifi:
  ssid: 'XXXXXXX'
  password: 'XXXXXX'
  domain : .visconti.nl
  
mqtt:
  broker: '192.168.3.100'
  port: 1883

  on_json_message:
    topic: controlpanel/status/led
    then:
        - lambda: |-
            int index = 0;
            float brightness = 50.0;
            int r = 100;
            int g = 100;
            int b = 100;
            if (x.containsKey("led_index")) {
                index = x["led_index"];
                light::FastLEDLightOutputComponent *fast_led = application_makefastledlight.fast_led;
                if (x.containsKey("led_bright"))
                    brightness = x["led_bright"];
                if ((index >= 0) && (index < fast_led->size())) {
                    if (x.containsKey("led_state")) {
                        if (x["led_state"] == "ON") {
                            if (x.containsKey("led_color")) {
                                r = x["led_color"]["r"];
                                g = x["led_color"]["g"];
                                b = x["led_color"]["b"];
                            }
                            ESP_LOGD("on_json_message", "LED index %d bright %f state ON", index, brightness);
                            light_fastled->turn_on();
                            fast_led->get_controller()->leds()[index].setRGB(r, g, b);
                            fast_led->get_controller()->leds()[index].maximizeBrightness(brightness);
                            fast_led->schedule_show();
                        } else if (x["led_state"] == "OFF") {
                            ESP_LOGD("on_json_message", "LED index %d state OFF", index);
                            fast_led->get_controller()->leds()[index].setRGB(0, 0, 0);
                            fast_led->schedule_show();
                        } else
                            ESP_LOGD("on_json_message", "INVALID value led_state");
                    }  else
                        ESP_LOGD("on_json_message", "INVALID missing led_state");
                } else
                    ESP_LOGD("on_json_message", "INVALID led_index out of bounds 0 < led_index < %d",fast_led->size());
            }
            else
                ESP_LOGD("on_json_message", "INVALID missing led_index");

# Enable logging
logger:
  level: DEBUG

ota:
  safe_mode: True
  password: VERYSECURE

i2c:
  sda: GPIO12
  scl: GPIO14
  scan: False

custom_component:
    - lambda: |-
        auto my_custom = new MyCustomComponent();
        return {my_custom};
  
light:
  - platform: fastled_clockless
    id: light_fastled
    chipset: WS2812B
    pin: GPIO4
    num_leds: 16
    rgb_order: GRB
    name: 'LED Strip'


```

**Traceback (if applicable):**

```
Dependency Graph
|-- <AsyncMqttClient> 0.8.2
|   |-- <ESPAsyncTCP> 1.2.0
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS>
|-- <FastLED> 3.2.0
|-- <Hash> 1.0
|-- <Wire> 1.0
|-- <esphomelib> 1.11.0-dev #0bea62d
|   |-- <ArduinoJson-esphomelib> 5.13.3
|   |-- <ESPAsyncTCP> 1.2.0
Compiling .pioenvs\controlpanel\src\main.cpp.o
In file included from .piolibdeps\esphomelib\src/esphomelib/application.h:53:0,
from src\main.cpp:3:
.piolibdeps\esphomelib\src/esphomelib/light/fast_led_light_output.h:44:18: warning: inline function 'virtual int32_t esphomelib::light::FastLEDLightOutputComponent::size() const' used but never defined [enabled by default]
inline int32_t size() const override;
^
In file included from C:\Users\m.vanturnhout\.platformio\packages\framework-arduinoespressif8266\cores\esp8266/Arduino.h:259:0,
from .piolibdeps\esphomelib\src/esphomelib/espmath.h:4,
from .piolibdeps\esphomelib\src/esphomelib/automation.h:5,
from .piolibdeps\esphomelib\src/esphomelib/application.h:7,
from src\main.cpp:3:
C:\Users\m.vanturnhout\.platformio\packages\framework-arduinoespressif8266\cores\esp8266/pgmspace.h:16:51: error: __c causes a section type conflict with __c
#define PSTR(s) (__extension__({static const char __c[] PROGMEM = (s); &__c[0];}))
^
C:\Users\m.vanturnhout\.platformio\packages\framework-arduinoespressif8266\cores\esp8266/WString.h:38:76: note: in definition of macro 'FPSTR'
#define FPSTR(pstr_pointer) (reinterpret_cast<const __FlashStringHelper *>(pstr_pointer))
^
C:\Users\m.vanturnhout\.platformio\packages\framework-arduinoespressif8266\cores\esp8266/WString.h:39:34: note: in expansion of macro 'PSTR'
#define F(string_literal) (FPSTR(PSTR(string_literal)))
^
.piolibdeps\esphomelib\src/esphomelib/log.h:75:55: note: in expansion of macro 'F'
#define ESPHOMELIB_LOG_FORMAT(tag, letter, format)  F(ESPHOMELIB_LOG_COLOR_ ## letter "[" #letter "][%s:%03u]: " format ESPHOMELIB_LOG_RESET_COLOR), tag, __LINE__
^
.piolibdeps\esphomelib\src/esphomelib/log.h:97:89: note: in expansion of macro 'ESPHOMELIB_LOG_FORMAT'
#define esph_log_d(tag, format, ...) esp_log_printf_(ESPHOMELIB_LOG_LEVEL_DEBUG, tag, ESPHOMELIB_LOG_FORMAT(tag, D, format), ##__VA_ARGS__)
^
.piolibdeps\esphomelib\src/esphomelib/log.h:152:29: note: in expansion of macro 'esph_log_d'
#define ESP_LOGD(tag, ...)  esph_log_d(tag, __VA_ARGS__)
^
src\my_custom_sensor.h:19:7: note: in expansion of macro 'ESP_LOGD'
ESP_LOGD("custom", "The GPIO pin 5 is HIGH!");
^
C:\Users\m.vanturnhout\.platformio\packages\framework-arduinoespressif8266\cores\esp8266/pgmspace.h:16:51: note: '__c' was declared here
#define PSTR(s) (__extension__({static const char __c[] PROGMEM = (s); &__c[0];}))
^
C:\Users\m.vanturnhout\.platformio\packages\framework-arduinoespressif8266\cores\esp8266/WString.h:38:76: note: in definition of macro 'FPSTR'
#define FPSTR(pstr_pointer) (reinterpret_cast<const __FlashStringHelper *>(pstr_pointer))
^
C:\Users\m.vanturnhout\.platformio\packages\framework-arduinoespressif8266\cores\esp8266/WString.h:39:34: note: in expansion of macro 'PSTR'
#define F(string_literal) (FPSTR(PSTR(string_literal)))
^
.piolibdeps\esphomelib\src/esphomelib/log.h:75:55: note: in expansion of macro 'F'
#define ESPHOMELIB_LOG_FORMAT(tag, letter, format)  F(ESPHOMELIB_LOG_COLOR_ ## letter "[" #letter "][%s:%03u]: " format ESPHOMELIB_LOG_RESET_COLOR), tag, __LINE__
^
.piolibdeps\esphomelib\src/esphomelib/log.h:97:89: note: in expansion of macro 'ESPHOMELIB_LOG_FORMAT'
#define esph_log_d(tag, format, ...) esp_log_printf_(ESPHOMELIB_LOG_LEVEL_DEBUG, tag, ESPHOMELIB_LOG_FORMAT(tag, D, format), ##__VA_ARGS__)
^
.piolibdeps\esphomelib\src/esphomelib/log.h:152:29: note: in expansion of macro 'esph_log_d'
#define ESP_LOGD(tag, ...)  esph_log_d(tag, __VA_ARGS__)
^
src\main.cpp:70:11: note: in expansion of macro 'ESP_LOGD'
ESP_LOGD("on_json_message", "INVALID missing led_index");
^
*** [.pioenvs\controlpanel\src\main.cpp.o] Error 1
 [ERROR] Took 7.67 seconds

```

**Additional information:**
