### ISSUE TITLE
Device Connects With Dynamic IP But Not Static

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [esphome/esphome#415]
**Operating environment (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266/Board/Sonoff):**

**Affected component:**

**Description of problem:**
When I compile and upload my YAML to the Sonoff Basic, I cannot get it to work with a static IP. If I comment out the manual_ip section of the configuration, the device connects to my AP with no issues however, if I try and connect with the manual_ip section below, it doesn't connect. I can confirm that my router's DHCP IP range is set from 1-100 so, 101 should be fine for a static IP. I have also done an nslookup and ping on port 101 and can confirm that there are no devices occupying that address.

**Problem-relevant YAML-configuration entries:**
```yaml
# Device Settings
esphomeyaml:
  name: dining_room_airwick_infuser
  platform: ESP8266
  board: esp01_1m

# WiFi Settings
wifi:
  ssid: OBSCURED_FOR_PROTECTION
  password: OBSCURED_FOR_PROTECTION
  manual_ip:
    static_ip: 192.168.1.101
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable Over The Air Flashing
ota:

# Define I/O
binary_sensor:
  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: True
    name: Dressing Room AirWick Infuser Button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: Dressing Room AirWick Infuser Relay
    id: relay
    pin:
      number: 12

output:
  - platform: esp8266_pwm
    id: led
    pin:
      number: 13
      inverted: True

light:
  - platform: monochromatic
    name: Dressing Room AirWick Infuser LED
    output: led
```

**Traceback (if applicable):**
<!--

--[11:10:24][I][wifi:179]: WiFi Connecting to '36_Whitney_Road'...
[11:10:30][W][wifi:727]: Event: Disconnected ssid='OBSCURED_FOR_PROTECTION' bssid=00:00:00:00:00:00 reason='AP Not Found'
[11:10:30][W][wifi:369]: Error while connecting to network.
[11:10:30][W][wifi:399]: Restarting WiFi adapter...>
```

```

**Additional information:**
N/A
