### ISSUE TITLE
yaml !include whole file

### ISSUE THREAD

**Issue by quazzie** [esphome/esphome#424]
Add ability to include a whole file in yaml.
```
test.yaml:
!include other.yaml
```

**Is your feature request related to a problem/use-case? Please describe.**

This would allow templating with substitutions.
base.yaml:
```
esphomeyaml:
  name: $hostname
  platform: ESP8266
  ...
```

node1.yaml:
```
substitutions:
  hostname: test
!include base.yaml
```

**Describe the solution you'd like:**

Top level !include in .yaml files

**Additional context:**
