### ISSUE TITLE
stepper.report_position code generator calls stepper.set_target on same action

### ISSUE THREAD

**Issue by s00500** [esphome/esphome#428]
**Operating environment (Hass.io/Docker/pip/etc.):**

Does not matter
**ESP (ESP32/ESP8266/Board/Sonoff):**

ESP8266

**Affected component:**

Stepper

**Description of problem:**
When I want to report the stepper position (in this case because I load the current_position global in the on_boot action) the code generator adds a **set_target** command on to the same action that was created for **report_position**

The line that causes this is line 123 in components/stepper/__init__.py
https://github.com/esphome/esphome/blob/463ad6f94b8e5d16070d0e248b703c11756632b2/esphomeyaml/components/stepper/__init__.py#L123

This always leads to the following compile error:

```
src/main.cpp: In function 'void setup()':
src/main.cpp:34:11: error: 'class esphomelib::stepper::ReportPositionAction<bool>' has no member named 'set_target'
action->set_target([=](NoArg x) -> int32_t {
^
```

**Problem-relevant YAML-configuration entries:**
```yaml
esphomeyaml:
  name: blind
  platform: ESP8266
  board: nodemcuv2
  on_boot:
    then:
      - stepper.report_position:
          id: main_stepper
          position: !lambda |-
            return id(current_position);
      - stepper.stepper.report_position:
          id: main_stepper
          target: !lambda |-
            return id(current_position);```

Now I really don't think that this is intended, please let me know, greetings from Vienna

**Traceback (if applicable):**
<!--
Please copy the traceback here if compilation is failing. If possible, also connect to the ESP and copy its logs into the backticks.
-->
```

```

**Additional information:**
